### ISSUE TITLE
Installation Failed - No matching distribution found for pysonar

### ISSUE THREAD

**Issue by amzar96** [SonarSource/sonar-scanner-python#45]
Hi,

I am facing issue during the installation using `pip`

Command:
1. `pip install pysonar`

Version:
1. Python - `3.9.19`

Error message
```bash
(ven) compass(development): pip install pysonar                                                                                                                                                        
ERROR: Could not find a version that satisfies the requirement pysonar (from versions: none)
ERROR: No matching distribution found for pysonar
```

**Comment by joke1196** [comment]
Hi @amzar96,

Thank you for your interest in the Sonar Scanner for Python.

Currently, the scanner is not yet released on PyPI, we are still figuring out a few details before the official release. I would advise you to continue using the [Sonar Scanner CLI](https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/scanners/sonarscanner/) in the meantime. 

I will close this issue as this will be solved once the official release is done, and the package is available on PyPI.
