### ISSUE TITLE
Not released to PyPi

### ISSUE THREAD

**Issue by v891** [SonarSource/sonar-scanner-python#67]
Hi, the library is unavailable in PyPi despite several attempts to release it. I'm curious when it will be available.

**Comment by guillaume-dequenne-sonarsource** [comment]
Hello, thank you for your feedback!

We've been having issues pushing the release to PyPI, which we hope will be solved in the next few days.

**Comment by ghislainpiot** [comment]
Hello,

We have finally released our scanner on [PyPi](https://pypi.org/project/pysonar-scanner/), and its name has been changed to `pysonar-scanner`.

We have updated the `README` with the new name.

Have a nice day
